"""production hardening: presence, streak history, task metadata, room themes

Revision ID: a1c4f7b92e30
Revises: 1972d2c1b807
Create Date: 2026-07-31

Hand-written rather than autogenerated so each change can say why it is
here. Every ALTER goes through batch_alter_table, which is a no-op wrapper
on Postgres and the table-rebuild dance SQLite needs — the same migration
therefore runs against Supabase and against a local grove.db.

WHAT THIS CHANGES

users
    + last_seen_at         presence. The old `is_online` boolean was never
                           set to True by any code path, so every user
                           appeared permanently offline on Friends and in
                           the Lobby. Online-ness is now derived from this
                           timestamp (see User.is_online).
    + show_online_status   lets a user hide presence without logging out.
    - is_online            replaced by the two columns above.
    - password_hash        always NULL. Supabase Auth owns credentials;
                           keeping an unused password column is a liability
                           with no corresponding benefit.

tasks
    + completed_at         when it was ticked off. The bare boolean could
                           not answer "what did I finish this week", which
                           is what the Streaks page shows.
    + due_date             gives the "Up Next" card something to order by.
    + index on user_id     every task query filters on it.

streaks
    + longest_count        so breaking a run does not erase the evidence it
                           ever happened.
    + total_days           lifetime active days.

streak_days (new)
    One row per user per active day: the history the Streaks heatmap draws,
    and the only way to audit a streak after the fact.

rooms
    + theme, capacity      the study-room themes and size limits the plan
                           lists; capacity NULL means unlimited.

friendships
    + responded_at         when a request was accepted or declined.
    + index on friend_id   "requests waiting on me" filters on it alone.
    + check not-self       enforces in the database what the service layer
                           already refuses to do.

room_memberships
    + index on room_id     "who is in this room".
"""

import sqlalchemy as sa
from alembic import op

revision = "a1c4f7b92e30"
# Chained after e4b7d28c6f31 (Turner's room preferences), not after
# 1972d2c1b807. Both revisions were written against the same parent, which
# would leave Alembic with two heads and `flask db upgrade` refusing to run.
down_revision = "e4b7d28c6f31"
branch_labels = None
depends_on = None


def upgrade():
    # ── users ───────────────────────────────────────────────────────────
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen_at", sa.DateTime(), nullable=True))
        # Added nullable with a server default, so existing rows get a value
        # without a separate backfill; the NOT NULL is applied after.
        batch_op.add_column(
            sa.Column(
                "show_online_status",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.drop_column("is_online")
        batch_op.drop_column("password_hash")

    # ── tasks ───────────────────────────────────────────────────────────
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("due_date", sa.Date(), nullable=True))
        batch_op.create_index("ix_tasks_user_id", ["user_id"], unique=False)

    # Every task already marked done predates completed_at. Backfilling from
    # created_at is a lie about the exact moment but keeps "completed tasks
    # have a completion time" true, which the stats queries rely on.
    op.execute(
        "UPDATE tasks SET completed_at = created_at WHERE completed = true AND completed_at IS NULL"
    )

    # ── streaks ─────────────────────────────────────────────────────────
    with op.batch_alter_table("streaks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("longest_count", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("total_days", sa.Integer(), nullable=False, server_default="0")
        )

    # An existing run is at least as long as the longest one ever recorded.
    op.execute("UPDATE streaks SET longest_count = current_count WHERE longest_count = 0")

    # ── streak_days ─────────────────────────────────────────────────────
    op.create_table(
        "streak_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False, server_default="1"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day", name="uq_streak_day"),
    )

    # ── rooms ───────────────────────────────────────────────────────────
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("theme", sa.String(length=20), nullable=False, server_default="grove")
        )
        batch_op.add_column(sa.Column("capacity", sa.Integer(), nullable=True))

    # ── friendships ─────────────────────────────────────────────────────
    with op.batch_alter_table("friendships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("responded_at", sa.DateTime(), nullable=True))
        batch_op.create_index("ix_friendships_friend_id", ["friend_id"], unique=False)
        batch_op.create_check_constraint("ck_friendship_not_self", "user_id != friend_id")

    # ── room_memberships ────────────────────────────────────────────────
    with op.batch_alter_table("room_memberships", schema=None) as batch_op:
        batch_op.create_index("ix_room_memberships_room_id", ["room_id"], unique=False)


def downgrade():
    with op.batch_alter_table("room_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_room_memberships_room_id")

    with op.batch_alter_table("friendships", schema=None) as batch_op:
        batch_op.drop_constraint("ck_friendship_not_self", type_="check")
        batch_op.drop_index("ix_friendships_friend_id")
        batch_op.drop_column("responded_at")

    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_column("capacity")
        batch_op.drop_column("theme")

    op.drop_table("streak_days")

    with op.batch_alter_table("streaks", schema=None) as batch_op:
        batch_op.drop_column("total_days")
        batch_op.drop_column("longest_count")

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_user_id")
        batch_op.drop_column("due_date")
        batch_op.drop_column("completed_at")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password_hash", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("is_online", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.drop_column("show_online_status")
        batch_op.drop_column("last_seen_at")
